### ISSUE TITLE
format exception : unexpected while register

### ISSUE THREAD

**Issue by Aneemes** [Frave07/ECommerce-Products-Flutter#1]
![271836594_1083320675855117_8692603358447658490_n](https://user-images.githubusercontent.com/52958998/150561402-7b70e7f2-67d9-4ebb-92ca-bf4573763fc2.jpg)

**Comment by Frave07** [comment]
Make sure that the database is created correctly and if you have modified any information make sure that you send the correct data.

for more information paint the error log by console.

**Comment by Aneemes** [comment]
![271836594_1083320675855117_8692603358447658490_n](https://user-images.githubusercontent.com/52958998/150668621-5c77ad83-9715-43c5-9259-b31f9cbeb17f.jpg)

**Comment by Aneemes** [comment]
![Capture](https://user-images.githubusercontent.com/52958998/150668650-8ad444fb-bd42-4ec4-ba4c-877f0a952ce6.PNG)
